### ISSUE TITLE
ModuleNotFoundError: No module named 'pipes' on 2022 LG CS 

### ISSUE THREAD

**Issue by rickkdotnet** [andrewfraley/magic_mapper#1]
It looks like the pipes module was removed from the newer firmwares. I have a 2022 LG CS running firmware 03.21.45 and it throws the following error: 

```
root@LGwebOSTV:~#   /usr/bin/python3 /home/root/magic_mapper.py
Traceback (most recent call last):
  File "/home/root/magic_mapper.py", line 6, in <module>
    import pipes
ModuleNotFoundError: No module named 'pipes'
root@LGwebOSTV:~# uname -a
Linux LGwebOSTV 5.4.96-266.mlt4tv.1 #1 SMP PREEMPT Fri Nov 25 04:25:18 UTC 2022 aarch64 GNU/Linux

```

I don't need the curl functionality so I just removed import and the curl function and without that the script is working fine.

**Comment by andrewfraley** [comment]
Ah sorry I've made a lot of changes recently that I haven't yet tested on my C2.  I did remove pipes already, though, so you're probably good to go now.  I'll test everything on the C2 again later this evening.

**Comment by andrewfraley** [comment]
tested properly on the C2 now, CS should be the same.
