### ISSUE TITLE
Please add to kill aplication

### ISSUE THREAD

**Issue by Majkysek** [andrewfraley/magic_mapper#13]
Please add function to kill aplication

**Comment by andrewfraley** [comment]
Hi @Majkysek , WebOS actually has support for an Exit button which isn't seen on the magic remote.  So if you're looking for a button to kill the currently in focus application, you can use the following. 

This would assign the Exit button to the red button on the magic remote.

```
"red": {
    "function": "press_button",
    "inputs": {
      "button": "exit"
    }
  }
```
