### ISSUE TITLE
Activating HUE lightscene via curl not working

### ISSUE THREAD

**Issue by PeeBeerBeach** [andrewfraley/magic_mapper#14]
I have a shell script that triggers a curl command to set a specific lightscene on my HUE lamps that works like a charm. I can execute it from my TV's CLI and it works just nicely.
Now i would like to map that to a button on the remote. For that purpose i chose the yellow button.
But somehow just nothing happens when i press yellow.

Here is my shell script:

>#!/bin/bash
>#Hue Szene Chill im Wohnzimmer einschalten
>curl -X PUT -d '{"scene": "myscene"}' http://192.168.1.122/api/NCXwWip0FaEUsfk5Up1oAKSl8g3Q8y4ThlULIozl/groups/2/action

and here my magic_mapper_config.json

>{
>  "yellow": {
>     "function": "curl",
>     "inputs": {
>     "url": "http://192.168.1.122/api/NCXwWip0FaEUsfk5Up1oAKSl8g3Q8y4ThlULIozl/groups/2/action",
>     "method": "PUT",
>     "data": "{\"scene\": \"myscene\"}" }
>  }
>}

What is wrong? How can i debug this?

The python script seems to be running fine. I can start it from CLI and there is no error output. So at least it confirms there is no malforming ;)

**Comment by PeeBeerBeach** [comment]
Actually my JSON is properly escaped but the escaping was removed from my post by the GIT forum.
It looks the same as yours.

**Comment by andrewfraley** [comment]
@PeeBeerBeach The best way to debug this is to first kill the running process:

Get the pid of the process (5387 in this case)
```
root@LGwebOSTV:~# ps aux | grep python
root      5387  0.0  0.1   9116  4420 ?        S    03:02   0:01 /usr/bin/python -u /home/root/magic_mapper.py
root     26294  0.0  0.0   4580   648 pts/5    S+   17:32   0:00 grep python
``` 

Kill the process
```
kill -9 5387
```

Run the script manually:

```
# *9 or *X models 
python magic_mapper.py

# *1, *2, *3 models
python3 magic_mapper.py
```

Then press your button and you should see something like:

```
root@LGwebOSTV:~# python magic_mapper.py
6 button down
6 button up
firing event for code: 7 button: 6
func_name: curl
Running curl command: curl -vs -X PUT -d {"scene": "myscene"} http://192.168.1.122/api/NCXwWip0FaEUsfk5Up1oAKSl8g3Q8y4ThlULIozl/groups/2/action
*   Trying 192.168.1.122...
```

If you see some errors let me know and also let me know what TV model you're using.  Also make sure you can manually run the curl command to see if it works.  Thanks!

**Comment by PeeBeerBeach** [comment]
Thanks Andrew!

I did all of this already.
The script starts but i get no output at all. I was expecting an output like you posted but then thought,  ok it seems to run fine maybe that is just normal.

The curl command works perfectly from CLI as stated in my first post here.

The TV model is OLED83C39LA - bought last year.
FW is Webos23 03.03.70

**Comment by PeeBeerBeach** [comment]
Actually i solved it.
It seems that on my TV or the WebOS version the input devices are mapped differently. I changed the input device in your script to this and now it works fine:

`INPUT_DEVICE = "/dev/input/event2"`

**Comment by PeeBeerBeach** [comment]
solved

**Comment by andrewfraley** [comment]
@PeeBeerBeach thanks for sharing!  I'll have to see if I can pick the right device automatically.  I have three different models of these TVs and all use the same device.

**Comment by PeeBeerBeach** [comment]
I am adding on to this as just recently my script stopped to work for me. Turned out that the event number for the TV remote had changed. So putting it to `INPUT_DEVICE = "/dev/input/event2"` it now works again.
I have in the meantime connected 2 PS4 Joypads to the TV and also deleted one out of the config again. So I assume the remote IDs might get reordered if you connect and disconnect other devices via bluetooth.

I am just reporting this because it might be interesting to understand.

Hope anybody reads it ;)
