### ISSUE TITLE
Support for switching inputs

### ISSUE THREAD

**Issue by kahkhang** [andrewfraley/magic_mapper#3]
Is it possible to add support for switching inputs (e.g. from TV to HDMI 1)? Happy to work on a PR if you point me in the right direction :)

**Comment by andrewfraley** [comment]
Hi, yes this can be added, we just need to find the endpoint for it.  I'll probably look for it tomorrow.  Just in case you're not aware, however, the remote has built in support to do this via the "quick select" functionality.  Hold down the 0 key and it will bring up the quick select menu, then you can create shortcuts for each of the other 9 number keys.  For example, if you assigned HDMI 1 to the number 1, you would then hold down number 1 to switch to HDMI 1.  You can also set quick select buttons for apps.

**Comment by kahkhang** [comment]
Thanks for the tip! I'm currently using the quick access, but that requires a long press and is flakey sometimes (i.e.  does not always work), so I'm wondering if overriding it via a short press would work better, and is also more convenient

**Comment by kahkhang** [comment]
I figured it out, no code changes are needed, here is my config

```
{
  "1": {
    "function": "launch_app",
    "inputs": {
      "app_id": "com.webos.app.hdmi1"
    }
  },
  "2": {
    "function": "launch_app",
    "inputs": {
      "app_id": "com.webos.app.livetv"
    }
  },
  "yellow": {
    "function": "launch_app",
    "inputs": {
      "app_id": "mediacorp.toggle2"
    }
  },
  "blue": {
    "function": "launch_app",
    "inputs": {
      "app_id": "youtube.leanback.v4"
    }
  }
}
```

**Comment by andrewfraley** [comment]
Great, thanks!  I'll update the documentation for this.
