### ISSUE TITLE
Disney button

### ISSUE THREAD

**Issue by GokuTD** [andrewfraley/magic_mapper#5]
Hi, so on G1 webos 6.3  firmware 3.34 i used button disney to launch emby app and is launching the app then is launching the store to install the disney app , what i'm missing ?

**Comment by GokuTD** [comment]
Ok, now my disney button is launching both apps , if the disney app is not installed will launch the instaling of disney app from the store and  launch the emby app ! if you know what file is configured to install the disney app i would like to modify it and replace it on every reboot with a simple script if returns the original file after reboot ! 
amazing job ,hope you continuing to personalize your webos , y wold like to put continue watching from emby instead of recomendations  ! 

Thank you  !!!

**Comment by andrewfraley** [comment]
Sorry, yes, this needs some more work for overriding the app buttons.  I’m working on a new method to take control of the remote’s input which should solve this.  It may be several days to a week before this will be available, though. Thanks!

**Comment by andrewfraley** [comment]
@GokuTD this may better suit your needs for the time being, you can install it from the HomeBrew app.  It's a little clunky, but works great to completely override any button.  https://repo.webosbrew.org/apps/org.webosbrew.inputhook

**Comment by GokuTD** [comment]
thank you so much , i had the app but didn't know how to use it and now i made it and works awsome for me , many thanks , good job !

**Comment by andrewfraley** [comment]
This works correctly now with magic_mapper.py (fixed in v0.2.0).
