### ISSUE TITLE
Question regarding sending RF commands

### ISSUE THREAD

**Issue by MonolithNZ** [andrewfraley/magic_mapper#7]
Hey there,

Thanks for putting this together! Truly amazing.

I've got an older amplifier linked to the magic remote via the device connector. The magic remote can power the amplifier on/off and adjust volume. Currently it;s a bit of a pain to power the amp on or off as it takes three button presses. 

Do you think it'd be possible to remap this function to a single button press via a Luna command?

Edit/ I should add that the amplifier is connected to the TV via optical only.

Thanks

**Comment by andrewfraley** [comment]
Yep you can do that with the send_ir_command function as documented here:
https://github.com/andrewfraley/magic_mapper#send_ir_command

**Comment by MonolithNZ** [comment]
Fantastic! Works like a charm. I saw that command in the readme yesterday but I didn't think it would work with RF based devices. You're an absolute legend!
