### ISSUE TITLE
send_cec_button

### ISSUE THREAD

**Issue by shivsey** [andrewfraley/magic_mapper#9]
I have tried applying the following example found in the Readme

`
  "...": {
    "function": "send_cec_button",
    "inputs": {
      "code": 18882561
    }
  }
`

I am getting the following output :

```
firing event for code: 994 button: ...
func_name: send_cec_button
running command: ['/usr/bin/luna-send', '-n', '1', 'luna://com.webos.service.tv.keymanager/createKeyEvent', '{"code": 18882561, "device": "remoteControl", "id": "magic_mapper", "type": "keyDown"}']
LUNASERVICE ERROR -1: Could not cancel to unknown client (_LSTransportAddPendingMessageWithToken @ transport.c:4125)
running command: ['/usr/bin/luna-send', '-n', '1', 'luna://com.webos.service.tv.keymanager/createKeyEvent', '{"code": 18882561, "device": "remoteControl", "id": "magic_mapper", "type": "keyUp"}']
LUNASERVICE ERROR -1: Could not cancel to unknown client (_LSTransportAddPendingMessageWithToken @ transport.c:4125)
```
The code does not seem to executing the home function on my Nvidia Shield TV and only displays the LG cursor

**Comment by andrewfraley** [comment]
They’ve changed the api endpoint on newer versions of webos.  The example should work on C9 as is, but I know the C2 needs a different endpoint and I haven’t updated it to support that yet.  Which model series do you have?  I’ll probably fix this on Friday or Saturday.

**Comment by shivsey** [comment]
Thanks for the quick reply.  I have a B2 and it has webOS 7.1.0-68, let me know if you need any other info.

**Comment by andrewfraley** [comment]
@shivsey Ok give the latest version a try, I have it working on a C2 with WebOS 7.3.0

**Comment by shivsey** [comment]
Works on my system as well, thanks!

**Comment by andrewfraley** [comment]
@shivsey that's actually due to the ... button, some buttons will automatically enable the mouse such as that one.  I may have a solution to that in the near future.

**Comment by shivsey** [comment]
No worries, take your time.  Just for the sake of clarity I've switched over to using the home button, but I'm guessing it follows the same attributes of the ... button.

`
"home": {
  "function": "send_cec_button",
    "inputs": {
      "code": 18882561
     }
},
`

Is there any documentation on other CEC commands, how did you find the code 18882561 executes the home function?

**Comment by andrewfraley** [comment]
Disable the script (or at least the ... mapping) and run:
    ls-monitor -f com.webos.service.eim

Switch your input to the device you want to find codes for, press the ... button, then choose the command to send (ie Home, Menu, etc).  Dig through the ls-monitor output looking for the key code.

**Comment by shivsey** [comment]
Thanks, I found the following codes, if it helps your documentation at all.

16777344 Play
16777349 Pause
16777345 Stop
16777413 Reverse
16777474 Fast Forward
18882566 Menu
18882561 Home
18882560 Power

As you mentioned they're kind of wash, the Menu and Power didn't seem to work with the Shield for me but all others functioned properly.

**Comment by andrewfraley** [comment]
@shivsey Thanks for those codes!  I added the mouse blocking functionality.  Edit the latest version of the script and change `BLOCK_MOUSE = True` at the top.  Note that this does disable the mouse completely, though, not just when you're pressing buttons that activate it.  I may try to improve this in the future, but due to the way the mouse works, it's difficult to only disable it when pressing buttons that activate it without causing erratic behavior, since the mouse remains activated on the remote side without the TV knowing.

**Comment by anishsane** [comment]
How did you find the codes for Play/Pause etc?
I found one code for EPG, but that was by an ugly brute-force method.

I am particularly looking for the CEC codes for number keys and channel +/- buttons. Sadly LG TV does not pass these keys via CEC by default. Only arrow, select, color keys are passed by direct remote button press.
That is the only reason I have used an IR-based mapping for my STB.
If I get the CEC codes for these keys, it will be very helpful.

**Comment by anishsane** [comment]
On a separate topic, is there a way I can compile python-cec for LG TV OS?

I tried building cec.so on my RaspberryPi Zero (also arm7, 32bit), but that did not work on the TV.
If we could build it, we can directly send the codes specified by cec-o-matic.com.
